[package]
name = "easy_private_voting_contract"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.9", directory = "noir-projects/aztec-nr/aztec" }
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }